export interface SheetSpec {
  readonly name: string;
  readonly headerRow?: number;
  readonly primaryColumn?: string;
  readonly fields?: ReadonlyArray<readonly [header: string, field: string]>;
}

const fields = (
  ...entries: Array<readonly [string, string]>
): ReadonlyArray<readonly [string, string]> => entries;

export const workbookSheetSpecs: readonly SheetSpec[] = [
  { name: "00 Guide" },
  { name: "01 Dashboard" },
  {
    name: "02 Gen 1 Roster",
    headerRow: 5,
    primaryColumn: "National Dex",
    fields: fields(
      ["Current Primary", "current_primary"],
      ["Current Secondary", "current_secondary"],
      ["National Dex", "national_dex"],
      ["Pokémon", "pokemon"],
      ["API Slug", "api_slug"],
      ["Current Typing", "current_typing"],
      ["Original Gen I Typing", "original_gen1_typing"],
      ["Type Changed?", "type_changed"],
      ["Evolution Family", "evolution_family"],
      ["Evolution Stage", "evolution_stage"],
      ["Genus", "genus"],
      ["Habitat", "habitat"],
      ["Height (m)", "height_m"],
      ["Weight (kg)", "weight_kg"],
      ["Base Stat Total", "base_stat_total"],
      ["HP", "hp"],
      ["Attack", "attack"],
      ["Defense", "defense"],
      ["Sp. Atk", "special_attack"],
      ["Sp. Def", "special_defense"],
      ["Speed", "speed"],
      ["Standard Abilities", "standard_abilities"],
      ["Hidden Ability", "hidden_ability"],
      ["Capture Rate", "capture_rate"],
      ["Base Friendship", "base_friendship"],
      ["Legendary?", "legendary"],
      ["Mythical?", "mythical"],
      ["Growth Rate", "growth_rate"],
      ["Shape", "shape"],
      ["Color", "color"],
      ["Pokédex Entry", "pokedex_entry"],
      ["PokéAPI Source", "pokeapi_source"],
    ),
  },
  {
    name: "03 Type Membership",
    headerRow: 5,
    primaryColumn: "National Dex",
    fields: fields(
      ["Type", "type"],
      ["Membership", "membership"],
      ["National Dex", "national_dex"],
      ["Pokémon", "pokemon"],
      ["Other Type", "other_type"],
      ["Type Fantasy", "type_fantasy"],
      ["Base Create Anchors", "base_create_anchors"],
      ["Candidate Job", "candidate_job"],
      ["Candidate Machine / Block", "candidate_machine_block"],
      ["Decision", "decision"],
      ["Status", "status"],
      ["Priority", "priority"],
      ["Explicit Owner", "explicit_owner"],
      ["Ownership / Handoff Notes", "ownership_handoff_notes"],
      ["Team Notes", "team_notes"],
      ["Source", "source"],
    ),
  },
  {
    name: "04 Type Workshop",
    headerRow: 5,
    primaryColumn: "Type",
    fields: fields(
      ["Type", "type"],
      ["Gen 1 Members", "gen1_members"],
      ["Primary Count", "primary_count"],
      ["Secondary Count", "secondary_count"],
      ["Core Worker Fantasy", "core_worker_fantasy"],
      ["Base Create Anchors", "base_create_anchors"],
      ["Non-Power Job Direction", "non_power_job_direction"],
      ["Visual & Audio Language", "visual_audio_language"],
      ["Balance Guardrail", "balance_guardrail"],
      ["Technical Risk", "technical_risk"],
      ["Confidence", "confidence"],
      ["Prototype Order", "prototype_order"],
      ["Decision", "decision"],
      ["Status", "status"],
      ["Priority", "priority"],
      ["Explicit Owner", "explicit_owner"],
      ["Ownership / Handoff Notes", "ownership_handoff_notes"],
      ["Team Notes", "team_notes"],
    ),
  },
  {
    name: "05 Pokemon Ideas",
    headerRow: 5,
    primaryColumn: "National Dex",
    fields: fields(
      ["National Dex", "national_dex"],
      ["Pokémon", "pokemon"],
      ["Current Typing", "current_typing"],
      ["Type Prompt", "type_prompt"],
      ["Natural Design Hooks", "natural_design_hooks"],
      ["Candidate Job", "candidate_job"],
      ["Create System", "create_system"],
      ["Specific Machine / Block", "specific_machine_block"],
      ["Worker Action / FX", "worker_action_fx"],
      ["Qualification Rule", "qualification_rule"],
      ["Inputs / Costs", "inputs_costs"],
      ["Output / Benefit", "output_benefit"],
      ["Stop / Pause Conditions", "stop_pause_conditions"],
      ["Throughput / Stress Cap", "throughput_stress_cap"],
      ["Progression Tier", "progression_tier"],
      ["Scope", "scope"],
      ["Feasibility", "feasibility"],
      ["Balance Risk", "balance_risk"],
      ["Decision", "decision"],
      ["Status", "status"],
      ["Priority", "priority"],
      ["Explicit Owner", "explicit_owner"],
      ["Ownership / Handoff Notes", "ownership_handoff_notes"],
      ["Related Task / Issue", "related_task_issue"],
      ["Team Notes", "team_notes"],
      ["Design QC", "design_qc"],
    ),
  },
  {
    name: "06 Create Catalog",
    headerRow: 5,
    primaryColumn: "System ID",
    fields: fields(
      ["System ID", "system_id"],
      ["System Family", "system_family"],
      ["Principal Create Components", "principal_create_components"],
      ["Best Pokémon Role Seam", "best_pokemon_role_seam"],
      ["Suggested Types", "suggested_types"],
      ["Machine Required?", "machine_required"],
      ["External Rotation?", "external_rotation"],
      ["Adapter Boundary", "adapter_boundary"],
      ["Balance / Abuse Risk", "balance_abuse_risk"],
      ["Lifecycle / Performance Risk", "lifecycle_performance_risk"],
      ["Prototype Direction", "prototype_direction"],
      ["Scope", "scope"],
      ["Research Status", "research_status"],
      ["Evidence URL", "evidence_url"],
      ["Explicit Owner", "explicit_owner"],
      ["Ownership / Handoff Notes", "ownership_handoff_notes"],
      ["Related Idea IDs", "related_idea_ids"],
      ["Team Notes", "team_notes"],
    ),
  },
  {
    name: "07 Idea Backlog",
    headerRow: 5,
    primaryColumn: "Idea ID",
    fields: fields(
      ["Idea ID", "idea_id"],
      ["Idea / Task", "idea_task"],
      ["Workstream", "workstream"],
      ["Related Dex / Type", "related_dex_type"],
      ["Create Target", "create_target"],
      ["Scope", "scope"],
      ["Status", "status"],
      ["Priority", "priority"],
      ["Effort", "effort"],
      ["Explicit Owner", "explicit_owner"],
      ["Ownership / Handoff Notes", "ownership_handoff_notes"],
      ["Suggested By", "suggested_by"],
      ["Next Action", "next_action"],
      ["Definition of Done", "definition_of_done"],
      ["Depends On", "depends_on"],
      ["Blocker / Decision Needed", "blocker_decision_needed"],
      ["Target Date", "target_date"],
      ["Evidence / Link", "evidence_link"],
      ["Team Notes", "team_notes"],
      ["QC", "qc"],
    ),
  },
  {
    name: "08 Sources & Lists",
    headerRow: 5,
    fields: fields(
      ["Source", "source"],
      ["URL", "url"],
      ["Used For", "used_for"],
      ["Checked", "checked"],
      ["", "separator_1"],
      ["", "separator_2"],
      ["", "separator_3"],
      ["", "separator_4"],
      ["", "separator_5"],
      ["STATUS", "status_values"],
      ["PRIORITY", "priority_values"],
      ["OWNER", "owner_values"],
      ["DECISION", "decision_values"],
      ["SCOPE", "scope_values"],
      ["FEASIBILITY", "feasibility_values"],
      ["RISK", "risk_values"],
      ["WORKSTREAM", "workstream_values"],
      ["EFFORT", "effort_values"],
    ),
  },
] as const;

export const quarantinedWorkbookFields = new Map([
  [
    "02 Gen 1 Roster/Pokédex Entry",
    "Potentially copyrighted flavor text; never publish or export to the mod.",
  ],
]);

export function expectedSheetNames(): string[] {
  return workbookSheetSpecs.map((sheet) => sheet.name);
}
